### ISSUE TITLE
Diseño de la base de datos

### ISSUE THREAD

**Issue by Alexis-26** [Alexis-26/Sensacine#27]
Planeación de la estructura de la base de datos a utilizar, con sus respectivas relaciones.

**Comment by Jacqueline-Lopez** [comment]
En el siguiente link se encuentra los diagramas en donde se refleja como se relaciono en cada una de la tablas para la base de datos
[https://lucid.app/lucidchart/aa70db07-d8e1-44d8-8b4c-899cf5b884b6/edit?viewport_loc=-1462%2C-633%2C4080%2C1800%2CXbkCT6YVmQ6k&invitationId=inv_4c7b935c-9783-4f31-8cbd-d5d373ca3fe8](url)
